# Generated by Django 5.0.6 on 2024-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_premium",
            field=models.BooleanField(default=False, help_text="Premium userlar uchun"),
        ),
    ]
