# Generated by Django 4.2.13 on 2024-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
