# Generated by Django 5.0.6 on 2024-06-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_adminuser_moderatoruser_studentuser_teacheruser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("email", "is_active")},
        ),
    ]
