# Generated by Django 4.2.13 on 2024-05-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="members/")),
                ("username", models.CharField(max_length=255)),
                ("website", models.URLField(max_length=255)),
                ("wallet_balance", models.FloatField()),
                ("income_amount", models.FloatField()),
                ("total_transaction", models.IntegerField()),
            ],
        ),
    ]
