# Generated by Django 5.0.6 on 2024-06-11 12:14

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_customproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="customproduct",
            name="created_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
