# Generated by Django 5.0.6 on 2024-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_customproduct_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customproduct",
            name="properties",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
