# Generated by Django 5.0.6 on 2024-06-11 12:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0007_customcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="customproduct",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
