# Generated by Django 5.0.6 on 2024-06-11 12:54
from django_ckeditor_5 import fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0007_customcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="customproduct",
            name="description",
            field=fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
